### ISSUE TITLE
CDDL or GPL license?

### ISSUE THREAD

**Issue by JaroslavTulach** [javaee/javahelp#45]
Hi.
I am helping the Apache incubation process of NetBeans and one of the issues we are solving is **JavaHelp** license (see [this email](https://lists.apache.org/thread.html/a3c047a068bd7f99a3c515cd89e2a72645965ae799c3be5a8b9739f0@%3Cdev.netbeans.apache.org%3E) for example). Apache and GPL licenses don't go well together...

I was thrilled to find out that there is this **JavaHelp** repository and that the source has been [released under CDDL license](https://github.com/javaee/javahelp/commit/3ca862d8626096770598a3a256886d205246f4a4#diff-9879d6db96fd29134fc802214163b95a) on Jul 19, 2017. Thank you @pranjal10!

However I'd like to point out that the headers of source files still carry on the old license. I would recommend to fix that as such thing may create confusion, uncertainty and be a reason why JavaEE will not be acceptable for the Eclipse foundation.

Of course I fully understand that the last change made on Jul 19, 2017 outweights the old commits made more than ten years ago and shows the current intention to **make JavaHelp available under CDDL license** and I plan to act according to that. Should such relicensing not be the Oracle desire (I assume @pranjal10 acts on behalf of Oracle), can you please express that here?  

Otherwise I plan to act with a goodwill  and **release CDDL licensed JavaHelp binary** by end of November 2017.

**Comment by romain-grecourt** [comment]
@edbratt @bshannon

**Comment by JaroslavTulach** [comment]
No visible comments so far. I take it as a confirmation of my previous conclusion that JavaHelp code isn't subject to GPL virality anymore.
